"""
Manic AI — Report Generator
Generates downloadable reports (PDF, Markdown) for department outputs.
"""

import os
import logging
import tempfile
from datetime import datetime
from typing import Literal

logger = logging.getLogger(__name__)


async def generate_report(
    department: str,
    content: str,
    task_prompt: str,
    output_format: Literal["pdf", "markdown", "html"] = "pdf",
) -> str:
    """
    Generate a downloadable report from department output.

    Args:
        department: Department key (e.g., "marketing_head")
        content: Department's output/result
        task_prompt: Original task prompt
        output_format: Output format (pdf, markdown, html)

    Returns:
        Path to generated report file
    """
    try:
        if output_format == "markdown":
            return await _generate_markdown_report(department, content, task_prompt)
        elif output_format == "html":
            return await _generate_html_report(department, content, task_prompt)
        elif output_format == "pdf":
            return await _generate_pdf_report(department, content, task_prompt)
        else:
            raise ValueError(f"Unsupported format: {output_format}")
    except Exception as e:
        logger.exception(f"Failed to generate {output_format} report: {e}")
        # Fallback to markdown
        return await _generate_markdown_report(department, content, task_prompt)


async def _generate_markdown_report(
    department: str, content: str, task_prompt: str
) -> str:
    """Generate a Markdown report."""
    from .org_chart import ORG_CHART

    dept_label = ORG_CHART.get(department, {}).get("label", department)
    timestamp = datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S UTC")

    markdown = f"""# {dept_label} Report

**Generated:** {timestamp}  
**Task:** {task_prompt}

---

## Executive Summary

{content}

---

## Details

### Original Request
{task_prompt}

### Department Analysis
{content}

---

*Report generated by Manic AI Orchestrator*
"""

    # Save to temp file
    with tempfile.NamedTemporaryFile(
        mode="w", suffix=".md", delete=False, prefix=f"manic_report_{department}_"
    ) as f:
        f.write(markdown)
        return f.name


async def _generate_html_report(department: str, content: str, task_prompt: str) -> str:
    """Generate an HTML report."""
    from .org_chart import ORG_CHART

    dept_label = ORG_CHART.get(department, {}).get("label", department)
    timestamp = datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S UTC")

    # Convert markdown-like content to HTML
    html_content = _markdown_to_html(content)

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{dept_label} Report</title>
    <style>
        body {{
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, sans-serif;
            line-height: 1.6;
            color: #333;
            max-width: 800px;
            margin: 0 auto;
            padding: 20px;
        }}
        h1 {{
            color: #2c3e50;
            border-bottom: 3px solid #3498db;
            padding-bottom: 10px;
        }}
        h2 {{
            color: #34495e;
            margin-top: 30px;
        }}
        .meta {{
            background: #ecf0f1;
            padding: 15px;
            border-radius: 5px;
            margin: 20px 0;
        }}
        .meta strong {{
            color: #2c3e50;
        }}
        .content {{
            background: #fff;
            padding: 20px;
            border-left: 4px solid #3498db;
        }}
        .footer {{
            margin-top: 40px;
            padding-top: 20px;
            border-top: 1px solid #ddd;
            font-size: 0.9em;
            color: #7f8c8d;
        }}
    </style>
</head>
<body>
    <h1>{dept_label} Report</h1>
    
    <div class="meta">
        <p><strong>Generated:</strong> {timestamp}</p>
        <p><strong>Task:</strong> {task_prompt}</p>
    </div>
    
    <h2>Executive Summary</h2>
    <div class="content">
        {html_content}
    </div>
    
    <h2>Details</h2>
    <h3>Original Request</h3>
    <p>{task_prompt}</p>
    
    <h3>Department Analysis</h3>
    <div class="content">
        {html_content}
    </div>
    
    <div class="footer">
        <p>Report generated by Manic AI Orchestrator</p>
    </div>
</body>
</html>
"""

    # Save to temp file
    with tempfile.NamedTemporaryFile(
        mode="w", suffix=".html", delete=False, prefix=f"manic_report_{department}_"
    ) as f:
        f.write(html)
        return f.name


async def _generate_pdf_report(department: str, content: str, task_prompt: str) -> str:
    """
    Generate a PDF report.
    Falls back to HTML if PDF generation fails.
    """
    try:
        # Try to use weasyprint for PDF generation
        import weasyprint

        # First generate HTML
        html_path = await _generate_html_report(department, content, task_prompt)

        # Convert HTML to PDF
        pdf_path = html_path.replace(".html", ".pdf")

        html = weasyprint.HTML(filename=html_path)
        html.write_pdf(pdf_path)

        # Clean up HTML file
        os.remove(html_path)

        return pdf_path

    except ImportError:
        logger.warning("weasyprint not installed, falling back to HTML report")
        return await _generate_html_report(department, content, task_prompt)
    except Exception as e:
        logger.error(f"PDF generation failed: {e}, falling back to HTML")
        return await _generate_html_report(department, content, task_prompt)


def _markdown_to_html(text: str) -> str:
    """Simple markdown to HTML conversion."""
    import re

    # Headers
    text = re.sub(r"^### (.*?)$", r"<h3>\1</h3>", text, flags=re.MULTILINE)
    text = re.sub(r"^## (.*?)$", r"<h2>\1</h2>", text, flags=re.MULTILINE)
    text = re.sub(r"^# (.*?)$", r"<h1>\1</h1>", text, flags=re.MULTILINE)

    # Bold
    text = re.sub(r"\*\*(.*?)\*\*", r"<strong>\1</strong>", text)

    # Italic
    text = re.sub(r"\*(.*?)\*", r"<em>\1</em>", text)

    # Line breaks
    text = text.replace("\n\n", "</p><p>")
    text = f"<p>{text}</p>"

    return text
